### ISSUE TITLE
bug: Surreal 2.0 syntax tracking issue & other issues

### ISSUE THREAD

**Issue by AlbertMarashi** [Ce11an/tree-sitter-surrealql#20]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-surrealql

### Describe the bug

- [ ] DEFINE INDEX `OVERWRITE`
- [ ] DEFINE TABLE `OVERWRITE`
- [ ] DEFINE FIELD `OVERWRITE`

![image](https://github.com/user-attachments/assets/1f3d4990-46f7-49c0-b6e8-b8c8cd416a13)

- [ ] `CONTAINS` keyword errors
```surql
DEFINE TABLE OVERWRITE user SCHEMAFULL
    PERMISSIONS
        FOR SELECT
            WHERE id = $auth
            OR ->member->organisation<-member<-user CONTAINS $auth
```

### Steps To Reproduce/Bad Parse Tree

-

### Expected Behavior/Parse Tree

-

**Comment by Ce11an** [comment]
Hey 👋🏻 

Thanks for opening an issue. As this project is _a work in progress_ there are many aspects of SurQL missing. Feel free to open a PR. If not, I'll keep this in mind the next time I'm free to work on it 🙂

**Comment by AlbertMarashi** [comment]
@Ce11an no problem, I may create a PR for it at some stage when I get the time.
